services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/cansat
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/cansat
    ports:
      - "3000:3000"
    depends_on:
      - backend

